# config/packages/knpu_oauth2_client.yaml
knpu_oauth2_client:
  clients:
    oidc:
      # must be "keycloak" - it activates that type!
      type: azure
      # add and set these environment variables in your .env files
      client_id: '%con4gis.oauth.oidc.client_id%'
      client_secret: '%con4gis.oauth.oidc.client_secret%'
      # a route name you'll create
      redirect_route: connect_oidc_check
      redirect_params: { }
      # Oidc server URL
      tenant: '%con4gis.oauth.oidc.realm%'
      url_login: '%con4gis.oauth.oidc.auth_server_url%'

      path_authorize: '/oauth2/v2.0/authorize'
      path_token: '/oauth2/v2.0/token'
      scope: ['openid', 'profile', 'email', 'idtoken']

      # Optional: Encryption algorith, i.e. RS256
      # encryption_algorithm: null
      # Optional: Encryption key path, i.e. ../key.pem
      # encryption_key_path: null
      # Optional: Encryption key, i.e. contents of key or certificate
      # encryption_key: null
      # whether to check OAuth2 "state": defaults to true
      # use_state: true